deploymentName: webapp-dev
namespace: dev
environment: development
port: 5050
replicaCount: 1
image:
  repository: 959975882219.dkr.ecr.us-east-1.amazonaws.com/tic_tac_toe
  tag: 5e7949188fe568220bdf53f40cfcef3aeb25f62e
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5050
# Simple ingress config without domain

ingress:
  enabled: true
  className: nginx
  path: /webapp-dev
  hostnames:
    - dev-webapp.local
  annotations: {}
  addRootPath: true # Only add this to one of your environments (prod or dev)
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

#
