deploymentName: webapp-prod
namespace: production
environment: production
port: 5050
replicaCount: 2 # usually prod has >1
image:
  repository: 959975882219.dkr.ecr.us-east-1.amazonaws.com/tic_tac_toe
  tag: 169ad56e583bac26eb4677c41d7c1dfd3ae86af2
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5050
ingress:
  enabled: true
  className: nginx
  path: /webapp-prod
  hostnames:
    - prod-webapp.local
  annotations: {}
  addRootPath: true # root path added only in prod
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
